// Generated by CoffeeScript 1.4.0
var log, query, queryAll, spawn,
  __slice = [].slice;

log = function() {
  var args, _ref;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return typeof console !== "undefined" && console !== null ? (_ref = console.log) != null ? typeof _ref.apply === "function" ? _ref.apply(console, args) : void 0 : void 0 : void 0;
};

query = function(identity) {
  return document.querySelector(identity);
};

queryAll = function(identity) {
  return document.querySelectorAll(identity);
};

spawn = function(str) {
  var c;
  c = document.createElement("div");
  c.innerHTML = str;
  return c.firstChild;
};

window.addEventListener("load", function() {
  var book_mark, chapter_mark, load_content, load_obj, req;
  window.home = query("#home");
  window.entries = query("#entries");
  window.content = query("#content");
  load_content = function(path) {
    var req;
    req = new XMLHttpRequest;
    req.open("get", "../fictions/" + path);
    req.send();
    return req.onload = function() {
      var add_line, lines, remove_line;
      lines = req.response.split("\n");
      add_line = function() {
        var elem, line;
        line = lines.shift();
        if (line != null) {
          if (line.trim().length === 0) {
            line = "¬";
          }
          elem = spawn("<div class='line'>" + line + "</div>");
          elem.onclick = book_mark;
          content.appendChild(elem);
          return setTimeout(add_line, 0);
        }
      };
      return (remove_line = function() {
        if (content.lastChild != null) {
          content.removeChild(content.lastChild);
          return setTimeout(remove_line, 0);
        } else {
          return add_line();
        }
      })();
    };
  };
  chapter_mark = function(e) {
    var elem, last;
    last = query(".chapter");
    if (last != null) {
      last.className = "entry";
    }
    elem = e.target;
    return elem.className = "entry chapter";
  };
  book_mark = function(e) {
    var elem, last;
    last = query(".mark");
    if (last != null) {
      last.className = "line";
    }
    elem = e.target;
    return elem.className = "line mark";
  };
  load_obj = function(obj) {
    entries.innerHTML = "";
    obj.dir.forEach(function(dir) {
      var elem;
      elem = spawn("<div class='entry'>" + dir.name + "/</div>");
      entries.appendChild(elem);
      return entries.lastChild.onclick = function() {
        return load_obj(dir.arr);
      };
    });
    return obj.arr.sort().forEach(function(file) {
      var elem;
      elem = spawn("<div class='entry'>" + file.name + "</div>");
      entries.appendChild(elem);
      return elem.onclick = function(e) {
        load_content(file.path);
        return chapter_mark(e);
      };
    });
  };
  req = new XMLHttpRequest;
  req.open("get", "../fictions/index.json");
  req.send();
  req.onload = function(res) {
    var json;
    json = JSON.parse(req.response);
    return (home.onclick = function() {
      return load_obj(json);
    })();
  };
  return load_content("sight-of-题叶/12-10-21-飞.fic");
});
